#!/bin/bash
cd ~
WORKSPACE_NAME="catkin_workspace"

mkdir -p ropod-project-software/${WORKSPACE_NAME}/src
cd ropod-project-software/${WORKSPACE_NAME}/src
git clone https://github.com/tue-ropod/tree-devpc.git ./
git checkout feature/remove_ed_dependency
sudo apt-get install python-wstool

cd ..
wstool init
cd src
wstool up
echo "source ~/ropod-project-software/${WORKSPACE_NAME}/src/platform/setup/devpc/setup.bash"  >> ~/.bashrc

source ~/ropod-project-software/${WORKSPACE_NAME}/src/platform/setup/devpc/setup.bash
rosdep update;rosdep install --from-path . -i -y;
cd ~/ropod-project-software/${WORKSPACE_NAME}; catkin_make;
